from datetime import date
from state import DocState
from utils.llm import call_llm
import config


SYSTEM_PROMPT = """\
You are a technical documentation writer. Generate comprehensive project documentation in Markdown format.

Use the provided analysis data to create documentation with these sections:
1. **Project Overview** - What the project does, its purpose
2. **Architecture** - High-level structure, key components, how they interact
3. **Setup & Installation** - Prerequisites, installation steps, environment variables
4. **Configuration** - Config files and their options
5. **API Reference** - Key modules, classes, functions (from the code summaries provided)
6. **Usage Examples** - How to run/use the project (infer from entry points and existing docs)
7. **Dependencies** - Production and dev dependencies with explanations
8. **Project Structure** - File tree with annotations

Write clear, professional documentation. If information is missing, note it as "To be documented" rather than guessing.
Do NOT wrap the entire output in a code block — output raw Markdown directly."""


def _format_summaries(label: str, items: list[dict]) -> str:
    if not items:
        return ""
    lines = [f"\n### {label}"]
    for item in items:
        lines.append(f"\n**{item['path']}**\n{item['summary']}")
    return "\n".join(lines)


def doc_generator(state: DocState) -> dict:
    existing_docs_text = ""
    for fname, content in state.get("existing_docs", {}).items():
        existing_docs_text += f"\n--- {fname} ---\n{content[:2000]}\n"

    deps_text = ""
    for fname, deps in state.get("dependencies", {}).items():
        deps_text += f"\n{fname}: {', '.join(deps[:30])}"

    user_prompt = f"""Project Analysis Data:

## Languages Detected
{', '.join(state.get('languages', ['Unknown']))}

## Frameworks Detected
{', '.join(state.get('frameworks', ['None detected']))}

## File Tree
```
{state.get('file_tree', 'Not available')[:3000]}
```

## Existing Documentation
{existing_docs_text[:3000] if existing_docs_text else 'None found'}

## Code Analysis
{_format_summaries('Entry Points', state.get('entry_points', []))}
{_format_summaries('Configuration Files', state.get('config_summaries', []))}
{_format_summaries('Key Modules', state.get('module_summaries', []))}

## Dependencies
{deps_text if deps_text else 'None found'}

## Dependency Analysis
{state.get('dependency_summary', 'Not available')}

Total lines of code: {state.get('total_lines', 'Unknown')}

Generate the complete project documentation now."""

    markdown = call_llm(SYSTEM_PROMPT, user_prompt, max_tokens=config.DOC_GEN_MAX_TOKENS, caller="Doc Generator")

    markdown += f"\n\n---\n*Generated by Doc Generator Agent on {date.today().isoformat()}*\n"

    return {"final_markdown": markdown}
